### ISSUE TITLE
HTPC Manager startup error, missing libssl on OMV 1.14 Kralizec

### ISSUE THREAD

**Issue by amitkeret** [cptjhmiller/OMV_Installers#9]
After upgrading to OMV 1.14, HTPC Manager doesn't work anymore.
I've uninstalled and re-installed, and still no go.

Output on manual startup:

```
# service HTPC_Manager start
Starting HTPC_Manager
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "Htpc.py", line 189, in <module>
    main()
  File "Htpc.py", line 121, in main
    from htpc.settings import Settings
  File "/root/Apps/HTPC_Manager/htpc/settings.py", line 7, in <module>
    import cherrypy
  File "/root/Apps/HTPC_Manager/libs/cherrypy/__init__.py", line 62, in <module>
    from cherrypy._cpcompat import urljoin as _urljoin, urlencode as _urlencode
  File "/root/Apps/HTPC_Manager/libs/cherrypy/_cpcompat.py", line 119, in <module>
    from md5 import new as md5
  File "/usr/local/lib/python2.7/md5.py", line 10, in <module>
    from hashlib import md5
ImportError: cannot import name md5
```

This was fixed with installing libssl:

```
# ldd /usr/local/lib/python2.7/lib-dynload/_hashlib.so
    linux-gate.so.1 =>  (0xb779a000)
    libssl.so.0.9.8 => not found
    libcrypto.so.0.9.8 => not found
    libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xb7772000)
    libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xb7623000)
    /lib/ld-linux.so.2 (0xb779b000)
# apt-get install libssl0.9.8
...
...
# ldd /usr/local/lib/python2.7/lib-dynload/_hashlib.so 
    linux-gate.so.1 =>  (0xb77de000)
    libssl.so.0.9.8 => /usr/lib/i686/cmov/libssl.so.0.9.8 (0xb7784000)
    libcrypto.so.0.9.8 => /usr/lib/i686/cmov/libcrypto.so.0.9.8 (0xb762c000)
    libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xb7612000)
    libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xb74c3000)
    libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xb74bf000)
    libz.so.1 => /lib/i386-linux-gnu/libz.so.1 (0xb74a6000)
    /lib/ld-linux.so.2 (0xb77df000)

# service HTPC_Manager start
Starting HTPC_Manager
2015-03-17 01:17:52 :: root :: INFO :: Welcome to HTPC-Manager!
```

Notice I had to install a specific version of libssl. When I tried `libssl`, I got and error message ("E: Package 'libssl' has no installation candidate").

**Comment by gry-613** [comment]
> After upgrading to OMV 1.14, HTPC Manager doesn't work anymore. I've uninstalled and re-installed, and still no go.
> 
> Output on manual startup:
> 
> ```
> # service HTPC_Manager start
> Starting HTPC_Manager
> ERROR:root:code for hash md5 was not found.
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/hashlib.py", line 139, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/usr/local/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type md5
> ERROR:root:code for hash sha1 was not found.
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/hashlib.py", line 139, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/usr/local/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha1
> ERROR:root:code for hash sha224 was not found.
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/hashlib.py", line 139, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/usr/local/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha224
> ERROR:root:code for hash sha256 was not found.
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/hashlib.py", line 139, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/usr/local/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha256
> ERROR:root:code for hash sha384 was not found.
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/hashlib.py", line 139, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/usr/local/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha384
> ERROR:root:code for hash sha512 was not found.
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/hashlib.py", line 139, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/usr/local/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha512
> Traceback (most recent call last):
>   File "Htpc.py", line 189, in <module>
>     main()
>   File "Htpc.py", line 121, in main
>     from htpc.settings import Settings
>   File "/root/Apps/HTPC_Manager/htpc/settings.py", line 7, in <module>
>     import cherrypy
>   File "/root/Apps/HTPC_Manager/libs/cherrypy/__init__.py", line 62, in <module>
>     from cherrypy._cpcompat import urljoin as _urljoin, urlencode as _urlencode
>   File "/root/Apps/HTPC_Manager/libs/cherrypy/_cpcompat.py", line 119, in <module>
>     from md5 import new as md5
>   File "/usr/local/lib/python2.7/md5.py", line 10, in <module>
>     from hashlib import md5
> ImportError: cannot import name md5
> ```
> 
> This was fixed with installing libssl:
> 
> ```
> # ldd /usr/local/lib/python2.7/lib-dynload/_hashlib.so
>     linux-gate.so.1 =>  (0xb779a000)
>     libssl.so.0.9.8 => not found
>     libcrypto.so.0.9.8 => not found
>     libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xb7772000)
>     libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xb7623000)
>     /lib/ld-linux.so.2 (0xb779b000)
> # apt-get install libssl0.9.8
> ...
> ...
> # ldd /usr/local/lib/python2.7/lib-dynload/_hashlib.so 
>     linux-gate.so.1 =>  (0xb77de000)
>     libssl.so.0.9.8 => /usr/lib/i686/cmov/libssl.so.0.9.8 (0xb7784000)
>     libcrypto.so.0.9.8 => /usr/lib/i686/cmov/libcrypto.so.0.9.8 (0xb762c000)
>     libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xb7612000)
>     libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xb74c3000)
>     libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xb74bf000)
>     libz.so.1 => /lib/i386-linux-gnu/libz.so.1 (0xb74a6000)
>     /lib/ld-linux.so.2 (0xb77df000)
> 
> # service HTPC_Manager start
> Starting HTPC_Manager
> 2015-03-17 01:17:52 :: root :: INFO :: Welcome to HTPC-Manager!
> ```
> 
> Notice I had to install a specific version of libssl. When I tried `libssl`, I got and error message ("E: Package 'libssl' has no installation candidate").

Hi, I'm having the same problem as you, but I already have the libssl.so.1.1 file in my /usr/local/anaconda/envs/python3.7/lib directory, so I don't know if I can use the apt-get install libssl0.9.8 command you mentioned above to install another one, so I'd like to ask you what happened at the time

**Comment by amitkeret** [comment]
I didn't have any `libssl` version installed prior to this error happening, so I was able to install the version specifically required.
I'm not sure if you should uninstall version 1.1 though, since it may be used by another application.
